#/bin/sh
# APP_LOCATION must be the appengine_staging directory of the app
# RUNTIME_LOCATION is the directory containing the 3 runtime jars for ex
#

# curl https://repo1.maven.org/maven2/com/google/appengine/runtime-deployment/2.0.9/runtime-deployment-2.0.9.zip -o runtime-deployment-2.0.9.zip

set -x

RUNTIME_DEPLOYMENT_ZIP="/home/lachlan/webtide/appengine-java-standard/runtime/deployment/target/runtime-deployment-2.0.10-SNAPSHOT.zip"
RUNTIME_DEPLOYMENT="/tmp/runtime-deployment"
mkdir -p $RUNTIME_DEPLOYMENT
rm -rf ${RUNTIME_DEPLOYMENT:?}/*
unzip $RUNTIME_DEPLOYMENT_ZIP -d $RUNTIME_DEPLOYMENT

# This is generated by using `mvn appengine:stage` command in root of the webapp project.
APP_LOCATION=/home/lachlan/webtide/gae-standard-demo/target/appengine-staging

# To start API Server you run this from root of appengine-java-standard repository.
# mvn exec:java -pl :appengine-apis-dev -Dexec.mainClass="com.google.appengine.tools.development.HttpApiServer"

"$JAVA_HOME"/bin/java \
 --add-opens java.base/java.lang=ALL-UNNAMED  \
 --add-opens java.base/java.nio.charset=ALL-UNNAMED \
 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 \
 -showversion -XX:+PrintCommandLineFlags \
 -Djava.class.path=$RUNTIME_DEPLOYMENT/runtime-main.jar \
 -Dclasspath.runtimebase=$RUNTIME_DEPLOYMENT: \
 com/google/apphosting/runtime/JavaRuntimeMainWithDefaults \
 --fixed_application_path=$APP_LOCATION  \
 $RUNTIME_DEPLOYMENT
